#!/usr/bin/env bash
#SBATCH --partition=batch_default
#SBATCH --cpus-per-task=28
#SBATCH --time=3-0:0:0
###SBATCH --nodelist=hopper
#SBATCH -o log/slurm.%j.%N.out # STDOUT
#SBATCH -e log/slurm.%j.%N.err # STDERR

module load anaconda/3
bootstrap_conda
conda activate p3env

which python
hostname
top -b -d1 -n1 | grep -i "%Cpu"
date
#for i in {900..999}
#do
#	python -u create_data.py $i
#done

#START=1200000
#TOTAL=100000
#EACH=25000
#SPLITS=$TOTAL/$EACH
#for (( i = 0; i < $SPLITS; i++ ))
#do
#	BEGIN=$(($i*$EACH+$START))
#	echo $BEGIN
#	python -u create_data.py $BEGIN $(($BEGIN+$EACH)) &
#done

python -u create_data.py $1 $2

wait
